config/routes.rb
Rails.application.routes.draw do
  
  resources :link_groups do
    resources :links
  end
  
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users, only: [:show]
  
  resources :friends

  
  
  root 'home#index'
  # root 'home#index'

  get 'home/about'

  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = current_user.friends
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized to Edit This Friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :emoji, :user_id)
    end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :first_name, style: "font-weight: bold;" %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"Steve" %>
  </div>

  <div class="form-group">
    <%= form.label :last_name, style: "font-weight: bold;" %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"Jobs" %>
  </div>

  <div class="field form-group">
    <%= form.label :emoji, style: "font-weight: bold;" %>
    <%= form.text_field :emoji, class:"form-control", placeholder:"📱" %>
  </div>

  <div class="field form-group">
    <%= form.label :email, style: "font-weight: bold;" %>
    <%= form.text_field :email, class:"form-control", placeholder:"steve@apple.com" %>
  </div>

  <div class="field form-group">
    <%= form.label :phone, style: "font-weight: bold;" %>
    <%= form.text_field :phone, class:"form-control", placeholder:"(123) 456-7890" %>
  </div>

  <div class="field form-group">
    <%= form.label :twitter, style: "font-weight: bold;" %>
    <%= form.text_field :twitter, class:"form-control", placeholder:"@SteveJobs" %>
  </div>

  <div class="field form-group">
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>

  <div>
    <%= form.submit class:"btn btn-outline-success btn-sm" %>
    <%= link_to "Cancel", friend, class:"btn btn-outline-secondary btn-sm" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<tr id="<%= dom_id friend %>">
  <td><%= link_to friend.emoji + " " + friend.first_name + " " + friend.last_name, friend %></td>
  <td><%= link_to "#{friend.email}", "mailto:#{friend.email}" %></td>
  <td><%= friend.phone %></td>
  <td><%= link_to "#{friend.twitter}", "https://twitter.com/#{friend.twitter}", target:"_blank" %></td>
  <td><%= button_to "Delete", 
          friend, method: :delete, 
          class: "btn btn-outline-danger btn-sm", 
          data: { 
            turbo_method: :delete, 
            turbo_confirm: "Are you sure?"
            } %></td>
  
</tr>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br/>

<%= button_to "Delete #{@friend.first_name}", 
    @friend, 
    method: :delete, 
    class:"btn btn-outline-danger btn-sm",
    data: {
        turbo_method: :delete, 
        turbo_confirm: "Are you sure?"
    } %>

app/views/friends/index.html.erb
<h1>My Friends</h1>

<br/>

<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th>Delete?</th>
    </tr>
  </thead>
  <tbody>
    <% @friends.each do |friend| %>
      <%= render partial: 'friend', locals: { friend: friend } %>
    <% end %>
  </tbody>
</table>

<%= link_to "New friend", new_friend_path, class:"btn btn-dark" %>

app/views/friends/new.html.erb
<h1>Add a New Friend</h1>

<br/>

<%= render "form", friend: @friend %>

app/views/friends/show.html.erb
<div class="card">
  <div class="card-header">
   <%= link_to "Back to Friends", friends_path %>
  </div>
  <div class="card-body">
    <h1 class="card-title"><%= @friend.emoji + " " + @friend.first_name + " " + @friend.last_name %></h1>

    <strong>Email:</strong>
    <%= link_to "#{@friend.email}", "mailto:#{@friend.email}" %>
    <br/>

    <strong>Phone:</strong>
    <%= @friend.phone %>
    <br/>

    <strong>Twitter:</strong>
    <%= link_to "#{@friend.twitter}", "https://twitter.com/#{@friend.twitter}", target:"_blank" %>
    <br/>

    <br/>

    <%= link_to "Edit #{@friend.first_name}'s Info", edit_friend_path(@friend), class:"btn btn-outline-secondary btn-sm" %>
    <%= button_to "Delete #{@friend.first_name}", 
        @friend, method: :delete, 
        class: "btn btn-outline-danger btn-sm",
        data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
        }%>
  </div>
</div>