config/routes.rb
Rails.application.routes.draw do
  
  resources :link_groups do
    resources :links
  end
  
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users, only: [:show]
  
  resources :friends

  
  
  root 'home#index'
  # root 'home#index'

  get 'home/about'

  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <%= link_to "Friends App", root_path, class:"navbar-brand" %>

  <% if user_signed_in? %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "My Friends", friends_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "My Links", link_groups_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
          <%= button_to "Logout", destroy_user_session_path, method: :delete, class:"btn btn-outline-light" %>
      </li>
    </ul>
    <div class="navbar-nav">
      <%= link_to user_path(current_user), class:"nav-link" do %>
        <% if current_user %>
          <span class="nav-item"><%= current_user.full_name %></span>
          <% if current_user.profile_picture.attached? %>
            <%= image_tag current_user.profile_picture, alt: "Profile Picture", class: "navbar-profile-pic" %>
          <% else %>
            <%= image_tag 'default_profile_picture.png', alt: "Default Profile Picture", class: "navbar-profile-pic" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
  <% else %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li>
        <%= link_to "About Us", home_about_path, class:"nav-link" %>
      </li>
    </ul>
    <div class="navbar-nav">
      <%= link_to "Login", new_user_session_path, class:"nav-link", style:"padding-right: 15px;" %>
      <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-light" %>
    </div>
  </div>
  <% end %>
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>

app/views/home/index.html.erb
<h1>Hello, world!</h1>
<p>This isn't quite my first rails page, but that's okay.</p>