config/routes.rb
Rails.application.routes.draw do
  
  resources :link_groups do
    resources :links
  end
  
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users, only: [:show]
  
  resources :friends

  
  
  root 'home#index'
  # root 'home#index'

  get 'home/about'

  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/link.rb
class Link < ApplicationRecord
    belongs_to :link_group
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, except: [:new, :create]
  before_action :set_link_group

  def show
  end

  # GET /links/new
  def new
    @link = @link_group.links.build
  
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links or /links.json
  def create
    @link = @link_group.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link_group, notice: "Link was successfully created." }
        format.json { render :show, status: :created, location: link_group_link_url(@link_group, @link) }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1 or /links/1.json
  def update

    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link_group, notice: "Link was successfully updated." }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1 or /links/1.json
  def destroy
    @link.destroy

    respond_to do |format|
      format.html { redirect_to @link_group, notice: "Link was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    def set_link_group
      @link_group = LinkGroup.find(params[:link_group_id])
    end

    # Only allow a list of trusted parameters through.
    def link_params
      params.require(:link).permit(:title, :url, :description, :link_group_id)
    end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<%= form_with(model: [@link_group, @link]) do |form| %>
  <% if link.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% link.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title, style: "font-weight: bold;" %>
    <%= form.text_field :title, class:"form-control", placeholder:"SpaceX" %>
  </div>

  <div class="form-group">
    <%= form.label :url, style: "font-weight: bold;" %>
    <%= form.text_field :url, class:"form-control", placeholder:"https://spacex.com" %>
  </div>

  <div class="form-group">
    <%= form.label :description, style: "font-weight: bold;" %>
    <%= form.text_area :description, class:"form-control", placeholder:"What's interesting about this link?" %>
  </div>

  <div>
    <%= form.submit class:"btn btn-success btn-sm" %>
    <%= link_to "Cancel", @link_group, class:"btn btn-outline-secondary btn-sm" %>
  </div>
  
<% end %>

app/views/links/_link.html.erb
<tr id="<%= dom_id link %>">
  <td><%= link.title %></td>
  <td><%= link_to link.url, title: "#{link.url}" %></td>

  <td><%= link_to "Edit", edit_link_group_link_path(link.link_group, link), class: "btn btn-secondary btn-sm" %></td>
  <td><%= link_to "Show", link_group_link_path(link.link_group, link), class: "btn btn-secondary btn-sm" %></td>

  <td><%= button_to "Delete", 
          [link.link_group, link], method: :delete, 
          class: "btn btn-outline-danger btn-sm", 
          data: { 
            turbo_method: :delete, 
            turbo_confirm: "Are you sure?"
          } %></td>
</tr>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render "form", link: @link %>

<br/>

<%= button_to "Delete", 
            [@link.link_group, @link], method: :delete, 
            class: "btn btn-outline-danger btn-sm", 
            data: { 
              turbo_method: :delete, 
              turbo_confirm: "Are you sure?"
            } %>

app/views/links/new.html.erb
<h1>Add a New Link</h1>

<br/>

<%= render "form", link: @link %>

app/views/links/show.html.erb
<div class="card">

  <div class="card-header">
    <%= link_to "Back to #{@link_group.title}", @link_group %>
  </div>

  <div class="card-body">
    <h1 class="card-title"><%= @link.title %></h1>
    <p><%= @link.description %></p>
    <%= link_to "Edit #{@link.title}", edit_link_group_link_path(@link_group, @link), class: "btn btn-outline-secondary btn-sm" %>

    <%= button_to "Delete #{@link.title}", 
          link_group_link_path(@link_group, @link), method: :delete, 
          class: "btn btn-outline-danger btn-sm",
          data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
          }%>
  </div>

</div>