config/routes.rb
Rails.application.routes.draw do
  
  resources :link_groups do
    resources :links
  end
  
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users, only: [:show]
  
  resources :friends

  
  
  root 'home#index'
  # root 'home#index'

  get 'home/about'

  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/link_group.rb
class LinkGroup < ApplicationRecord
    
    belongs_to :user
    has_many :links, dependent: :destroy
    
end

app/controllers/link_groups_controller.rb
class LinkGroupsController < ApplicationController
  before_action :set_link_group, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  # GET /link_groups or /link_groups.json
  def index
    @link_groups = current_user.link_groups
  end

  # GET /link_groups/1 or /link_groups/1.json
  def show
    @link_group = LinkGroup.find(params[:id])
  end

  # GET /link_groups/new
  def new
    # @link_group = LinkGroup.new
    @link_group = current_user.link_groups.build
  end

  # GET /link_groups/1/edit
  def edit
  end

  # POST /link_groups or /link_groups.json
  def create
    # @link_group = LinkGroup.new(link_group_params)
    @link_group = current_user.link_groups.build(link_group_params)

    respond_to do |format|
      if @link_group.save
        format.html { redirect_to link_group_url(@link_group), notice: "Link group was successfully created." }
        format.json { render :show, status: :created, location: @link_group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @link_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /link_groups/1 or /link_groups/1.json
  def update
    respond_to do |format|
      if @link_group.update(link_group_params)
        format.html { redirect_to link_group_url(@link_group), notice: "Link group was successfully updated." }
        format.json { render :show, status: :ok, location: @link_group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @link_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /link_groups/1 or /link_groups/1.json
  def destroy
    @link_group.destroy

    respond_to do |format|
      format.html { redirect_to link_groups_url, notice: "Link group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @link_group = current_user.link_groups.find_by(id: params[:id])
    redirect_to link_groups_path, notice: "Not Authorized to Edit This Link Group" if @link_group.nil?
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link_group
      @link_group = LinkGroup.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def link_group_params
      params.require(:link_group).permit(:title, :user_id, :link_group_id, :description, :emoji)
    end
    
end

app/helpers/link_groups_helper.rb
module LinkGroupsHelper
end

app/views/link_groups/_form.html.erb
<%= form_with(model: link_group) do |form| %>
  <% if link_group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(link_group.errors.count, "error") %> prohibited this link_group from being saved:</h2>

      <ul>
        <% link_group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title, style:"display: block" %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :emoji, style:"display: block" %>
    <%= form.text_field :emoji, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description, style:"display: block" %>
    <%= form.text_area :description, class:"form-control" %>
  </div>

  <div>
    <%= form.submit class:"btn btn-success btn-sm" %>
    <%= link_to "Cancel", link_group, class:"btn btn-outline-secondary btn-sm" %>
  </div>

<% end %>

app/views/link_groups/_link_group.html.erb
<div id="<%= dom_id link_group %>">
  <p>
    <strong>Title:</strong>
    <%= link_group.emoji.present? ? "#{link_group.emoji} #{link_group.title}" : link_group.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= link_group.description %>
  </p>

</div>

app/views/link_groups/edit.html.erb
<h1>Edit Link Group</h1>

<%= render "form", link_group: @link_group %>

app/views/link_groups/index.html.erb
<h1>Link Groups</h1>

<div id="link_groups">
  <% @link_groups.each do |link_group| %>
    <%= render link_group %>
    <p>
      <%= link_to "Show this link group", link_group %>
    </p>
  <% end %>
</div>

<%= link_to "New link group", new_link_group_path, class:"btn btn-dark" %>

app/views/link_groups/new.html.erb
<h1>New Link Group</h1>

<%= render "form", link_group: @link_group %>

app/views/link_groups/show.html.erb
<div class="card">

  <div class="card-header">
    <%= link_to "Back to Link Groups", link_groups_path %>
  </div>

  <div class="card-body">
    <h1 class="card-title"><%= @link_group.emoji.present? ? "#{@link_group.emoji} #{@link_group.title}" : @link_group.title %></h1>

    <p><strong>Description: </strong><%= @link_group.description %></p>

    <%= link_to "Edit #{@link_group.title}", edit_link_group_path(@link_group), class:"btn btn-outline-secondary btn-sm" %>
    <%= button_to "Delete #{@link_group.title}", 
          @link_group, method: :delete, 
          class: "btn btn-outline-danger btn-sm",
          data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
          }%>

    <br><br>

    <div id="links">

      <h2><%= "#{@link_group.title} Links" %></h2>

      <table class="table table-hover">
        <thead class="thead-dark">
          <tr>
            <th>Title</th>
            <th>URL</th>
            <th colspan="3">Actions</th>
          </tr>
        </thead>
        <tbody>
          <%= render partial: 'links/link', collection: @link_group.links, as: :link %>
        </tbody>
      </table>

      <%= link_to "Add a Link", new_link_group_link_path(@link_group), class:"btn btn-outline-secondary btn-sm" %>

    </div>

</div>